### ISSUE TITLE
Bloodborne: I only see a quarter of the screen. Any ideas?

### ISSUE THREAD

**Issue by CLAPIOTE2024** [shadps4-emu/shadPS4#1081]
Hello:
all my drivers are up to date, the game is fluid, but only on a quarter of the screen. Has anyone had this **problem?**
![image](https://github.com/user-attachments/assets/e4b042c4-0fd8-4ac7-9b8f-425c53e696e7)

**Comment by rafael-57** [comment]
Did you apply a resolution patch without restarting?

**Comment by CLAPIOTE2024** [comment]
doesn't change anything.

**Comment by CLAPIOTE2024** [comment]
OK now, My screen resolution was 4k, it works when i change my resolution to 1920*1080.


it's weird though

**Comment by rafael-57** [comment]
> doesn't change anything.

I didn't tell you to do it, I was asking if you had done it. Try checking your GPU scaling settings, maybe you have set it to no scaling.

**Comment by Hermiten** [comment]
Can you try again on the last build ? Normally this is fixed with some new commits

**Comment by CLAPIOTE2024** [comment]
nope.
![image](https://github.com/user-attachments/assets/a87b9808-8224-46c0-a980-1d9e36dbc0ab)
(sorry for the delay)

**Comment by Hermiten** [comment]
Do a new fresh install , remove everything (config, etc ..)

**Comment by CLAPIOTE2024** [comment]
still no change after fresh install
![image](https://github.com/user-attachments/assets/4ac468ca-ab34-4c5b-add5-03148549205a)

i repeat: it works on 1980*1024, but not in 4k

**Comment by killerdave56** [comment]
Just put the scale at 100% in windows screen option.
