### ISSUE TITLE
The emulator stopped running after installing the Win 10 x64 KB5043064 update. 

### ISSUE THREAD

**Issue by tr3m0r** [shadps4-emu/shadPS4#1129]
On September 12, the update was installed and the emulator stopped running. Before that, everything was fine, but now a black window just opens without any messages and even the emulator interface itself with a list of games does not open. 

The logs folder is empty. 

Running any downloaded version of the emulator, even from another folder, does not bring results — everything is exactly the same.

Deleting the user folder in the directory shadPS4.exe does not bring results.

CrashDumps file attached.

https://github.com/user-attachments/assets/e57a6e94-8b56-4bcf-aa88-bb58335a18d6

![image4](https://github.com/user-attachments/assets/fa2592e4-e738-4e0e-b744-8b5aa6597995)
![image5](https://github.com/user-attachments/assets/51f120b6-8818-4a28-b493-de6b5ea8e89d)
![image2](https://github.com/user-attachments/assets/5aed4f49-49c2-4085-bbe4-f1cf0225a60d)
[shadPS4.exe.18184.dmp](https://github.com/user-attachments/files/17175355/shadPS4.exe.18184.dmp)

**Comment by DanielSvoboda** [comment]
Recently a problem with 'different characters' was fixed, have you tested it in pre-release?
In the print you are using version 0.2.0, we are already at 0.3.1
https://github.com/shadps4-emu/shadPS4/releases

**Comment by tr3m0r** [comment]
I've tried many of the most recent builds. I download a new one almost every day.
![Screenshot 2024-09-29 013214](https://github.com/user-attachments/assets/75669cc9-418f-4d12-8ca9-3f41c9f4248c)
And, until September 12th, I didn't have the slightest problem with running the emulator. I started and played Bloodborne without any problems.
The path to the emulator folder does not contain non-Latin characters.

**Comment by tr3m0r** [comment]
I just downloaded this version [shadps4-win64-qt-2024-09-28-545e94d](https://github.com/shadps4-emu/shadPS4/releases/download/Pre-release-shadPS4-2024-09-28-545e94d/shadps4-win64-qt-2024-09-28-545e94d.zip) unpacked it into a new folder, the result is still the same

https://github.com/user-attachments/assets/658da0ff-d80c-4770-b3d8-344a456c33d3

**Comment by troubleNZ** [comment]
you need to change folder permissions, or launch as an administrator every time.
do the following to resolve.
run cmd as administrator, type "explorer ." so it opens an explorer window as administrator. navigate to the folder.
Right click, Select Properties. security tab.
Change / Edit
Select "Users", tick Modify and Apply/Ok. Ok. and it should now work.

**Comment by tr3m0r** [comment]
It didn't help, unfortunately

https://github.com/user-attachments/assets/137a67f9-bc76-44e3-8aa3-3b681d21f30a

**Comment by Hermiten** [comment]
On your video , you try shadps4 0.2.0 but you said that you downloaded the version from 3 days ago and this one is the 0.3.1 so please test again with the last version

**Comment by tr3m0r** [comment]
> On your video , you try shadps4 0.2.0

No, it's not 0.2.0, it's just the folder name. I've tryed many versions, but since September 12 no one of them running.
The versions released after 02 october now launching the UI, but do not start the game:

https://github.com/user-attachments/assets/43e07562-ffbf-428a-9161-d10a3e547747

But before September 12 I've played Bloodborne successfully on the same PC, none of the configuration changed since, none of the folders moved, etc.

![Screenshot 2024-10-07 131352](https://github.com/user-attachments/assets/815a4394-7352-4c7f-9cce-ffb29c068573)

**Comment by Attila101** [comment]
having the same issue after updating win11, i even reset my entire pc to fix this and failed. it doesnt work anymore, please this should be fixed.

**Comment by tr3m0r** [comment]
Idk the true reason why this happened, but I have found a solution to my problem.

I started xenia canary and saw the error message msvcp140.dll and I decided to reinstall the redistributable package of C++ libraries. 
Now everything works as before. The reason why the problem occurred is not clear to me, the libraries were definitely installed before that and everything worked. But, fortunately, in this situation, shadPS4 itself turned out to have nothing to do with it at all.

Tnx to all! Closed.
